### ISSUE TITLE
Suggested setup has issues when rerunning the Lambda in quick succession

### ISSUE THREAD

**Issue by AdalbertKhoolsaat** [aws-samples/aws-lambda-smb-shares#1]
As I'm working on a case very similar to what is described in the AWS Blog related to this repo, I took this setup as initial reference along with some best practices taken from the SMBLibrary repo itself. 

One problem I have come across is that there appear to be issues pertaining to (re-)connecting when running the Lambda multiple times in quick succession. 

Basic flow for every interaction with Fsx is as follows:

**1 - Establish session**
   - Connect To Host
   - Login To Host
   - TreeConnect To Share
  
**2 - Interact with file and/or directory**
   - CreateFile, ReadFile, WriteFile, QueryDirectory
   - CloseFile (always)

**3 - fully repeat (2) in case of successive interactions**

**4 - End session**
  - Disconnect Share (= FileStore)
  - Log Off From Host
  - Disconnect From Host
   
This works on a single run, but establishing a new session for a second run within ~5 minutes consistently results in problems.
When _Disconnect From Host_ is part of ending the session, establishing the new session will fail on _Connect To Host_-step. If we only _Log Off From Host_ when ending a session, establishing a new session will instead fail on _Login To Host_-step. 

I cannot reproduce this issue locally with the Mock Lambda Test Tool. It always successfully establishes a new session even within seconds of ending the previous run.

What could be the reason for this behavior and, more importantly, what could be the solution?

**Comment by ryanaprofessional** [comment]
I am also having this issue.  Has there been any resolution?

**Comment by ryanaprofessional** [comment]
I solved a similar problem today.  The issue was that we were using client as an instance variable and lambda does not new up a function each time.  This means that the instance variables are reused and the constructor is not called.  The re using of the client caused connection issues.  Moving the client to a local variable inside the lambda fixed the problem.

**Comment by AdalbertKhoolsaat** [comment]
@ryanaprofessional , thank you for responding. I can confirm that the source of and solution for my issue was pretty much identical to your case. 

The class using SMB2Client was refactored to work with DI, taking ISMBClient as parameter which we registered as Transient.
In my case this resolved the issue.
